#!/bin/bash

TMPD=$(mktemp -d)

trap "rm -rf '$TMPD'" EXIT

rm -rf dist/client
mkdir -p dist/client
OUT_ZIP=$PWD/dist/client/build.zip

cd "$TMPD" &>/dev/null
ln -s ../../.git/config build-info.txt
# zip -q build.zip *
zip -q --symlinks "$OUT_ZIP" *
